load("@rules_python//python:py_library.bzl", "py_library")

package(
    default_visibility = ["//sphinxdocs:__subpackages__"],
)

py_library(
    name = "sphinx_bzl",
    srcs = glob(["*.py"]),
    imports = [".."],
    # Allow depending on it in sphinx_binary targets
    visibility = ["//visibility:public"],
)
