module(
    name = "multi_python_versions",
)

bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_python", version = "0.0.0")
bazel_dep(name = "platforms", version = "0.0.11")

local_path_override(
    module_name = "rules_python",
    path = "../..",
)

uv = use_extension("@rules_python//python/uv:uv.bzl", "uv")
uv.configure(version = "0.12.1")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(
    # The environment variable takes precedence if set.
    python_version = "3.10",
    python_version_env = "BAZEL_PYTHON_VERSION",
)

PYTHON_VERSIONS = [
    "3.10",
    "3.11",
    "3.12",
    "3.13",
    "3.14",
]

[
    python.toolchain(
        configure_coverage_tool = True,
        python_version = v,
    )
    for v in PYTHON_VERSIONS
]

use_repo(
    python,
    "pythons_hub",
    python = "python_versions",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
use_repo(pip, "pypi")

[
    pip.parse(
        hub_name = "pypi_multi",
        python_version = v,
        requirements_lock = "//requirements:requirements.txt",
    )
    for v in PYTHON_VERSIONS
]

# example test dependencies
bazel_dep(name = "rules_shell", version = "0.2.0", dev_dependency = True)

# Only needed to make rules_python's CI happy. rules_java 8.3.0+ is needed so
# that --java_runtime_version=remotejdk_11 works with Bazel 8.
bazel_dep(name = "rules_java", version = "8.16.1")
