name: mypy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      - uses: jpetrucciani/mypy-check@master
        with:
          python_version: 3.8
          path: 'src-d/rules_python/python/runfiles'
      - uses: jpetrucciani/mypy-check@master
        with:
          python_version: 3.8
          path: 'tests/runfiles'
